---
title: "Recursos Iniciais para Começar a Matéria"
author: "James R. Hunter"
date: "31 de janeiro 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Aqui é uma lista dos recursos que temos disponíveis para ajudar vocês participar na matéria.

Anote bem: Este documento e a maioria dos seguintes está sendo preparado diretamente em RStudio.


## Repositório dos Programas, Informações e Documentos para a Matéria

Nós vamos usar **Github** (www.github.com), um dos repositórios mais populares no mundo de data science hoje em dia.

Vocês precisam ir para o site de Github e criar uma conta, seguindo as instruções na página inicial.

Depois, podem ir para página do índice do curso (https://github.com/jameshunterbr/MAD-CBt1) para fazer o download dos documentos que precisa (inclusive este). 

Lá, eu depositarei todos os slides, programas, documentos de apoio, etc. durante o curso. 

Vocês podem download eles ou clonar o site para seu repositório no Github.

## Canal de Videos

No **YouTube**, criei um canal de videos relacionados à matéria. A maioria seriam menos de 5 minutos e eles vão explicar um ponto especifico. Por exemplo, o primeiro explica como instalar R e RStudio no seu computador. 

## Khan Academy

Para vocês que são puros iniciantes em estatística ou precisam um reforço, criei um link para Khan Academy, um dos melhores recursos para aprendizagem das matérias técnicas ou exatas. Nosso curso terá acesso às aulas de estatística básica. Se vocês fazem os exercícios lá, posso monitorar seu desempenho (e seus problemas). As aulas de Khan Academy formaram parte de sua nota. A maioria das aulas sobre estatística tem uma tradução em português.

Para entrar nas aulas relacionadas ao nosso curso, abre uma conta no site (https://pt.khanacademy.org), clique em seu nome no canto superior a direta na tela (depois que confirma a inscrição no seu email). Clique no item no menu de **"Perfil"** . Agora, clique na aba de "Tutores". Nesta página, onde diz "Adicionar um professor", entre o código: `4QY68Y`. 

Você pode entrar no ensinamento de Estatística diretamente agora. Simplesmente, vá para sua tela "Página Inicial" e vai ver a matéria de "Estatística de Ensino Médio". 

Não tem um horário fixo para fazer esses lições, mas se você fazé-las mais rápido possível, pode focar nos elementos da matéria mais avançados.

## Horas de Encontro (Office Hours)

Estarei disponível todos as quintas de 13.30h até 16h para os alunos da aula. Não está necessário marcar em avanço.
Meu escritório fica no Prédio de Pesquisa 2, Rua Pedro de Toledo, 669, 6º Andar fundos.